AcadOracle/AcadOracle.WebMVC/Controllers/CursoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcadOracle.Dal.Interfaces;
using AcadOracle.DomainModel.Models;
using AcadOracle.WebMVC.Models;

namespace AcadOracle.WebMVC.Controllers
{   
    public class CursoesController : Controller
    {
		private readonly ICursoRepository cursoRepository;

		// If you are using Dependency Injection, you can delete the following constructor
        private CursoesController()
        {
        }

        public CursoesController(ICursoRepository cursoRepository)
        {
			this.cursoRepository = cursoRepository;
        }

        //
        // GET: /Cursoes/

        public ViewResult Index()
        {
            return View(cursoRepository.AllIncluding(curso => curso.Disciplinas));
        }

        //
        // GET: /Cursoes/Details/5

        public ViewResult Details(int id)
        {
            return View(cursoRepository.Find(id));
        }

        //
        // GET: /Cursoes/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Cursoes/Create

        [HttpPost]
        public ActionResult Create(Curso curso)
        {
            if (ModelState.IsValid) {
                cursoRepository.InsertOrUpdate(curso);
                cursoRepository.Save();
                return RedirectToAction("Index");
            } else {
				return View();
			}
        }
        
        //
        // GET: /Cursoes/Edit/5
 
        public ActionResult Edit(int id)
        {
             return View(cursoRepository.Find(id));
        }

        //
        // POST: /Cursoes/Edit/5

        [HttpPost]
        public ActionResult Edit(Curso curso)
        {
            if (ModelState.IsValid) {
                cursoRepository.InsertOrUpdate(curso);
                cursoRepository.Save();
                return RedirectToAction("Index");
            } else {
				return View();
			}
        }

        //
        // GET: /Cursoes/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View(cursoRepository.Find(id));
        }

        //
        // POST: /Cursoes/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            cursoRepository.Delete(id);
            cursoRepository.Save();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                cursoRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AcadOracle/AcadOracle.WebMVC/Controllers/DisciplinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcadOracle.Dal;
using AcadOracle.Dal.Interfaces;
using AcadOracle.DomainModel.Models;
using AcadOracle.WebMVC.Models;

namespace AcadOracle.WebMVC.Controllers
{   
    public class DisciplinaController : Controller
    {
		private readonly IDisciplinaRepository disciplinaRepository;
        private readonly ICursoRepository cursoRepository;
        
        public DisciplinaController(IDisciplinaRepository disciplinaRepository, ICursoRepository cursoRepository)
        {
			this.disciplinaRepository = disciplinaRepository;
            this.cursoRepository = cursoRepository;
        }

        //
        // GET: /Disciplina/

        public ViewResult Index()
        {
            return View(disciplinaRepository.AllIncluding(disciplina => disciplina.Turmas, disciplina => disciplina.Cursoes, disciplina => disciplina.PreRequisitos, disciplina => disciplina.RequisitoPara));
        }

        //
        // GET: /Disciplina/Details/5

        public ViewResult Details(int id)
        {
            return View(disciplinaRepository.Find(id));
        }

        //
        // GET: /Disciplina/Create

        //public ActionResult Create()
        //{
        //    ViewBag.CursoList = new SelectList(cursoRepository.All.ToArray(), "Id", "Nome");
            
        //    return View();
        //}

        public ActionResult Create(int? cursoId)
        {
            if(cursoId != null && cursoId.HasValue)
                ViewBag.CursoList = new SelectList(cursoRepository.All.ToArray(), "Id", "Nome", cursoId.Value);
            else
                ViewBag.CursoList = new SelectList(cursoRepository.All.ToArray(), "Id", "Nome");

            return View();
        }

        //
        // POST: /Disciplina/Create

        [HttpPost]
        public ActionResult Create(Disciplina disciplina)
        {
            if (ModelState.IsValid) {
                disciplinaRepository.InsertOrUpdate(disciplina);
                disciplinaRepository.Save();
                return RedirectToAction("Index");
            } else {
				return View();
			}
        }
        
        //
        // GET: /Disciplina/Edit/5
 
        public ActionResult Edit(int id)
        {
             return View(disciplinaRepository.Find(id));
        }

        //
        // POST: /Disciplina/Edit/5

        [HttpPost]
        public ActionResult Edit(Disciplina disciplina)
        {
            if (ModelState.IsValid) {
                disciplinaRepository.InsertOrUpdate(disciplina);
                disciplinaRepository.Save();
                return RedirectToAction("Index");
            } else {
				return View();
			}
        }

        //
        // GET: /Disciplina/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View(disciplinaRepository.Find(id));
        }

        //
        // POST: /Disciplina/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            disciplinaRepository.Delete(id);
            disciplinaRepository.Save();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                disciplinaRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AcadOracle/AcadOracle.WebMVC/Views/Cursoes/Create.cshtml
@model AcadOracle.DomainModel.Models.Curso

@{
    ViewBag.Title = "Create";
}

<h2>Criar</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Curso</legend>

		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AcadOracle/AcadOracle.WebMVC/Views/Cursoes/Delete.cshtml
@model AcadOracle.DomainModel.Models.Curso

@{
    ViewBag.Title = "Deletar";
}

<h2>Deletar</h2>

<h3>Tem certeza que deseja deletar o curso?</h3>
<fieldset>
    <legend>Curso</legend>

    <div class="display-label">Nome</div>
    <div class="display-field">@Model.Nome</div>

    <div class="display-label">Disciplinas</div>
    <div class="display-field">@(Model.Disciplinas == null ? "None" : Model.Disciplinas.Count.ToString())</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Voltar para a lista", "Index")
    </p>
}

AcadOracle/AcadOracle.WebMVC/Views/Cursoes/Details.cshtml
@model AcadOracle.DomainModel.Models.Curso

@{
    ViewBag.Title = "Detalhes do Curso";
}

<h2>Details</h2>

<fieldset>
    <legend>Curso</legend>

    <div class="display-label">Nome</div>
    <div class="display-field">@Model.Nome</div>

    <div class="display-label">Disciplinas (@Html.ActionLink("Add", "Create", "Disciplina", new {cursoId = Model.Id}, null))</div>
    <div class="display-field">@(Model.Disciplinas == null ? "None" : Model.Disciplinas.Count.ToString())</div>
</fieldset>
<p>
    @Html.ActionLink("Editar", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Voltar para a lista", "Index")
</p>

AcadOracle/AcadOracle.WebMVC/Views/Cursoes/Edit.cshtml
@model AcadOracle.DomainModel.Models.Curso

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Curso</legend>

        @Html.HiddenFor(model => model.Id)
		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AcadOracle/AcadOracle.WebMVC/Views/Cursoes/Index.cshtml
@model IEnumerable<AcadOracle.DomainModel.Models.Curso>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th></th>
        <th>
            Nome
        </th>
        <th>
            Disciplinas
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
        <td>
			@item.Nome
        </td>
        <td>
			@(item.Disciplinas == null ? "None" : item.Disciplinas.Count.ToString())
        </td>
    </tr>
}

</table>

AcadOracle/AcadOracle.WebMVC/Views/Cursoes/_CreateOrEdit.cshtml
@model AcadOracle.DomainModel.Models.Curso

@* This partial view defines form fields that will appear when creating and editing entities *@

<div class="editor-label">
    @Html.LabelFor(model => model.Nome)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.Nome)
    @Html.ValidationMessageFor(model => model.Nome)
</div>