AcadOracle/AcadOracle.WebMVC/Controllers/OracleServiceController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using AcadOracle.Core.Interfaces;
using AcadOracle.Dal.Interfaces;
using AcadOracle.DomainModel;
using AcadOracle.DomainModel.Models;
using AcadOracle.DomainModel.Restricao;
using AcadOracle.WebMVC.Infrastructure.ActionFilters;
using AcadOracle.WebMVC.Models;
using AcadOracle.WebMVC.Models.Extensions;

namespace AcadOracle.WebMVC.Controllers
{
    public class OracleServiceController : Controller
    {
        private readonly IOracleService oracleService;
        private readonly ICursoRepository cursoRepository;
        private readonly IDisciplinaRepository disciplinaRepository;

        public OracleServiceController(IOracleService oracleService, ICursoRepository cursoRepository,
                                       IDisciplinaRepository disciplinaRepository)
        {
            this.oracleService = oracleService;
            this.cursoRepository = cursoRepository;
            this.disciplinaRepository = disciplinaRepository;
        }
        //
        // GET: /SugerirDisciplinas/

        public ActionResult Create()
        {
            IEnumerable<Curso> cursos = cursoRepository.All.ToArray();
            ViewBag.CursoList = new SelectList(cursos, "Id", "Nome");

            IEnumerable<Disciplina> cursadas = new Disciplina[0];
            IEnumerable<Disciplina> pendentes =  disciplinaRepository.GetPendentesECursadas(cursos.First(), cursadas);

            RequisicaoSugestaoModel model = new RequisicaoSugestaoModel();
            model.Disponiveis = new MultiSelectList(pendentes, "Id", "Nome");


            return View(model);
        }

        [HttpPost]
        public ActionResult Create(RequisicaoSugestaoModel result)
        {
            var restricoes = GetRestricoes(result);
            var cursadas = result.CursadasId != null ? disciplinaRepository.All.Where(d => result.CursadasId.Any(c => c == d.Id)).ToArray() : new Disciplina[0];
            var candidatas = disciplinaRepository.GetPendentes(new Curso() { Id = result.CursoId }, cursadas);

            var turmas = oracleService.SugerirDisciplinas(candidatas, cursadas, restricoes);

            if (turmas.Any())
            {
                var data = new RouteValueDictionary();
                var counter = 0;

                foreach (var turma in turmas)
                {
                    data.Add("id"+counter, turma.ToString());
                    counter++;
                }

                data.Add("id" + counter, string.Format("Total de créditos: {0}", turmas.Sum(t => t.Disciplina.Creditos)));

                return RedirectToAction("Show", data);
            }
            result.NoResultsFound = true;

            IEnumerable<Curso> cursos = cursoRepository.All.ToArray();
            ViewBag.CursoList = new SelectList(cursos, "Id", "Nome");
            IEnumerable<Disciplina> pendentes = disciplinaRepository.GetPendentesECursadas(new Curso() { Id = result.CursoId } , cursadas);
            result.Disponiveis = new MultiSelectList(pendentes, "Id", "Nome");

            
            return View(result);
        }

        private IEnumerable<Restricao> GetRestricoes(RequisicaoSugestaoModel from)
        {
            List<Restricao> restricoes = new List<Restricao>();

            if (from.RestricaoDisciplinasId != null && from.RestricaoDisciplinasId.Any())
            {
                IEnumerable<Disciplina> disciplinas =
                    disciplinaRepository.All.Where(d => from.RestricaoDisciplinasId.Contains(d.Id)).ToArray();
                RestricaoDisciplinas restricaoDisciplina = new RestricaoDisciplinas(disciplinas);

                restricoes.Add(restricaoDisciplina);
            }

            if (from.RestricaoCreditos > 0)
            {
                RestricaoCreditos creditos = new RestricaoCreditos(from.RestricaoCreditos);
                restricoes.Add(creditos);
            }

            if (from.RestricaoHorarios != null)
            {
                var turmaHorarios = from.RestricaoHorarios.ToTurmaHorarios();
                if (turmaHorarios != null && turmaHorarios.Any())
                {
                    RestricaoHorarios horarios = new RestricaoHorarios(turmaHorarios);
                    restricoes.Add(horarios);
                }
            }

            return restricoes;
        }

        [BindArray]
        public ActionResult Show(string[] turmas)
        {
            return View(turmas);
        }

        [HttpPost]
        public JsonResult GetDisciplinasPendentes(DisciplinasRequestModel disciplinas)
        {
            IEnumerable<Disciplina> cursadas = disciplinas.CursadasId != null ? disciplinas.CursadasId.Select(x => new Disciplina() {Id = x }).ToArray() : new Disciplina[0];
            IEnumerable<Disciplina> pendentes = disciplinaRepository.GetPendentesECursadas(new Curso() { Id = disciplinas.CursoId}, cursadas);

            CursadasResponseView result = new CursadasResponseView();
            result.CursadasId = disciplinas.CursadasId;
            result.Disciplinas = pendentes.Select(x => new KeyValuePair<string, int>(x.Nome, x.Id));

            return Json(result);
        }

    }
}

AcadOracle/AcadOracle.WebMVC/Controllers/TurmaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcadOracle.Dal;
using AcadOracle.Dal.Interfaces;
using AcadOracle.DomainModel;
using AcadOracle.DomainModel.Models;
using AcadOracle.WebMVC.Models;
using Moo;

namespace AcadOracle.WebMVC.Controllers
{   
    public class TurmaController : Controller
    {
		private readonly IDisciplinaRepository disciplinaRepository;
		private readonly ITurmaRepository turmaRepository;

	
        public TurmaController(IDisciplinaRepository disciplinaRepository, ITurmaRepository turmaRepository)
        {
			this.disciplinaRepository = disciplinaRepository;
			this.turmaRepository = turmaRepository;
        }

        //
        // GET: /Turma/

        public ViewResult Index()
        {
            return View(turmaRepository.AllIncluding(turma => turma.Disciplina));
        }

        //
        // GET: /Turma/Details/5

        public ViewResult Details(int id)
        {
            return View(turmaRepository.Find(id));
        }

        //
        // GET: /Turma/Create

        public ActionResult Create()
        {
			ViewBag.PossibleDisciplinas = disciplinaRepository.All;
                return View();
        } 

        //
        // POST: /Turma/Create

        [HttpPost]
        public ActionResult Create(TurmaEditModel turma)
        {
            if (ModelState.IsValid)
            {
                var result = turma.MapTo<Turma>();
                result.TurmaHorarios = turma.TurmaHorario.ToTurmaHorarios();

                turmaRepository.InsertOrUpdate(result);
                turmaRepository.Save();
                return RedirectToAction("Index");
            } else {
				ViewBag.PossibleDisciplinas = disciplinaRepository.All;
				return View();
			}
        }
        
        //
        // GET: /Turma/Edit/5
 
        public ActionResult Edit(int id)
        {
			ViewBag.PossibleDisciplinas = disciplinaRepository.All;

            Turma turma = turmaRepository.Find(id);

            return View(turma.MapTo<TurmaEditModel>());
        }

        //
        // POST: /Turma/Edit/5

        [HttpPost]
        public ActionResult Edit(TurmaEditModel turma)
        {
            if (ModelState.IsValid)
            {
                var result = turma.MapTo<Turma>();
                
                turmaRepository.InsertOrUpdate(result);
                turmaRepository.Save();
                return RedirectToAction("Index");
            } else {
				ViewBag.PossibleDisciplinas = disciplinaRepository.All;
				return View();
			}
        }

        //
        // GET: /Turma/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View(turmaRepository.Find(id));
        }

        //
        // POST: /Turma/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            turmaRepository.Delete(id);
            turmaRepository.Save();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                disciplinaRepository.Dispose();
                turmaRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AcadOracle/AcadOracle.WebMVC/Views/OracleService/Create.cshtml
@model AcadOracle.WebMVC.Models.RequisicaoSugestaoModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
<script type="text/javascript" language="javascript" src="~/Scripts/oracleService.js"></script>

@if (Model.NoResultsFound)
{
    <script type="text/javascript">
        $(document).ready(function() {
            showNoResultsFoundMessage();
        }) 
    </script>
}


@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
<fieldset>
    <legend>Sugestão de Disciplinas</legend>
        
    <div class="editor-label">
        <b>Selecione o curso:</b>
    </div>
    <div class="editor-field">
        @Html.DropDownListFor(m => m.CursoId, (SelectList)ViewBag.CursoList)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.Disponiveis, "Disciplinas Disponíveis:")
        Marque as disciplinas que você já cursou.
    </div>

    <div class="editor-field">
        @Html.ListBoxFor(m => m.CursadasId, Model.Disponiveis, new { title="Marque as disciplinas que você já cursou.", style="width: 310px;" })
        <br/>
        <input type="button" value="Atualizar Cursadas" id="btnReload"/>
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(m => m.RestricaoDisciplinasId, "Restrições Disciplinas:")
        Marque as disciplinas que você não deseja cursar.
    </div>

    <div class="editor-field">
        @Html.ListBoxFor(m => m.RestricaoDisciplinasId, Model.Disponiveis, new { title="Marque as disciplinas que você não deseja cursar.", style="width: 310px;" })
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(m => m.RestricaoCreditos, "Máximo de créditos:")
    </div>

    <div class="editor-field">
        @Html.TextBoxFor(m => m.RestricaoCreditos, new { title = "o default é 24, caso esse campo fique vazio."})    
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(m => m.RestricaoHorarios, "Horários que não desejo cursar:")
        No formato 2jk (segunda jk), 5lm(quinta lm), etc...
    </div>

    <div class="editor-field">
        @Html.TextBoxFor(m => m.RestricaoHorarios, new { title = "No formato 2jk (segunda jk), 5lm(quinta lm), etc..."})    
    </div>
    
    <p>
        <input type="submit" value="Consultar Sugestão" />
    </p>
</fieldset>
}

<div id="dialog-message" title="Nenhuma Sugestão" style="display: none;">
  <p>
    <span class="ui-icon ui-icon-circle-check" style="float: left; margin: 0 7px 50px 0;"></span>
    Não há disciplinas disponíveis para as disciplinas selecionadas. 
  </p>
  <p>
    Adicione mais turmas @Html.ActionLink("aqui", "Create", "Turma") .
  </p>
</div>

AcadOracle/AcadOracle.WebMVC/Views/OracleService/Show.cshtml
@model IEnumerable<string>
@{
    ViewBag.Title = "Show";
}

<h2>Sugestão de turmas:</h2>

@foreach (var turma in Model)
{
    <br/>
    @turma
}
<br/>

<div>
    @Html.ActionLink("Voltar para os filtros", "Create")
</div>